# Generates .NET .resx resource files from i18n/source/<locale>.json (spec
# §9: "generate each platform's native format from it" -- ".resx/
# equivalent for Windows"). Mirrors generate-apple-strings.py's shape and
# role, but written in PowerShell rather than Python: this Windows dev
# box has no working Python install (confirmed directly -- `python`/
# `python3` only resolve to the Microsoft Store app-execution-alias
# stub, not a real interpreter), and PowerShell is already this
# project's own native Windows tooling choice (every other
# apps/windows/Scripts/*.ps1 generator). Writing this as .py and leaving
# it unverified would contradict this project's core practice of
# verifying tooling live rather than assuming it works.
#
# "en" is written as the neutral resx (Strings.resx, no culture suffix)
# -- the default/fallback culture .NET's ResourceManager falls back to
# when a satellite is missing a key or missing entirely -- since English
# is this project's primary source language. Every other locale becomes
# a satellite resx (Strings.<locale>.resx), which the .NET SDK compiles
# into a satellite resource assembly at build time automatically (.resx
# files under a project directory are implicitly embedded -- confirmed
# via a real build, not assumed).
#
# One platform-specific transform: Apple's "%@" positional placeholder
# (used by exactly one key, duality.option3.confirmation_field_format)
# becomes .NET's "{0}" for use with string.Format -- see Strings.cs's
# Format() helper.
#
# Usage: powershell -File i18n/generate-resx-strings.ps1
$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Split-Path -Parent $ScriptDir
$SourceDir = Join-Path $RepoRoot "i18n\source"
$OutDir = Join-Path $RepoRoot "apps\windows\VaultSignerUI\VaultSignerUI\Resources"
$NeutralLocale = "en"

New-Item -ItemType Directory -Path $OutDir -Force | Out-Null

function Escape-Xml([string]$Value) {
    return [System.Security.SecurityElement]::Escape($Value)
}

Get-ChildItem -Path $SourceDir -Filter "*.json" | Sort-Object Name | ForEach-Object {
    $locale = $_.BaseName
    $entries = Get-Content -Raw -Encoding UTF8 $_.FullName | ConvertFrom-Json

    if ($locale -eq $NeutralLocale) {
        $outPath = Join-Path $OutDir "Strings.resx"
    } else {
        $outPath = Join-Path $OutDir "Strings.$locale.resx"
    }

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add('<?xml version="1.0" encoding="utf-8"?>')
    # XML comments can't contain "--" (confirmed by a real build failure,
    # MSB3103/XmlException, not assumed). Also avoiding any non-ASCII
    # character literally in this .ps1 file's own source: Windows
    # PowerShell 5.1 mis-decoded a stray em dash here without a BOM,
    # corrupting this line and every line after it into a parse error
    # (also confirmed live, not assumed) -- plain ASCII only in source.
    $lines.Add("<!-- Generated by i18n/generate-resx-strings.ps1 from i18n/source/$locale.json. Do not hand-edit. -->")
    $lines.Add('<root>')
    $lines.Add('  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>')
    $lines.Add('  <resheader name="version"><value>2.0</value></resheader>')
    $lines.Add('  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>')
    $lines.Add('  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>')

    $keyCount = 0
    foreach ($prop in $entries.PSObject.Properties) {
        $key = $prop.Name
        if ($key.StartsWith("_")) { continue }
        $keyCount++
        # Only duality.option3.confirmation_field_format uses this today --
        # a single "%@" positional placeholder, always the 0th (and only)
        # format argument, so a plain replace is exact.
        $value = $prop.Value.ToString().Replace('%@', '{0}')
        $lines.Add("  <data name=`"$(Escape-Xml $key)`" xml:space=`"preserve`">")
        $lines.Add("    <value>$(Escape-Xml $value)</value>")
        $lines.Add("  </data>")
    }
    $lines.Add('</root>')

    [System.IO.File]::WriteAllLines($outPath, $lines, [System.Text.UTF8Encoding]::new($false))
    Write-Host "wrote $($outPath.Substring($RepoRoot.Length + 1)) ($keyCount keys)"
}
