#!/usr/bin/env python3
"""Generates Android string resources from i18n/source/<locale>.json (spec
§9: "generate each platform's native format from it"). Run this whenever a
source/*.json file changes, before the next Gradle build (Gradle doesn't
watch this file itself — there's no build-time hook, unlike
apps/android/app/build.gradle.kts's UniFFI bindings task, since this is a
plain source-file generator matching i18n/generate-apple-strings.py's own
shape, not something Gradle needs to re-run per build).

Dotted keys (e.g. "welcome.subtitle") become valid Android resource names
by replacing "." with "_" ("welcome_subtitle") — Android resource names
may not contain ".". Apple's "%@" placeholder syntax is converted to
Android's positional "%1$s", "%2$s", ... form (required once a string has
more than one substitution, and good practice even with exactly one, since
Android string resources aren't guaranteed positional otherwise).

Usage: python3 i18n/generate-android-strings.py
"""
import json
import pathlib
import re

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE_DIR = REPO_ROOT / "i18n" / "source"
OUT_DIR = REPO_ROOT / "apps" / "android" / "app" / "src" / "main" / "res"


def resource_name(key: str) -> str:
    return key.replace(".", "_").replace("-", "_")


def convert_placeholders(value: str) -> str:
    index = 0

    def replace(_match: "re.Match[str]") -> str:
        nonlocal index
        index += 1
        return f"%{index}$s"

    return re.sub(r"%@", replace, value)


def escape(value: str) -> str:
    value = convert_placeholders(value)
    value = value.replace("\\", "\\\\").replace('"', '\\"').replace("'", "\\'")
    value = value.replace("\n", "\\n")
    # A bare '%' Android doesn't recognize as a format spec would still be
    # parsed as one and crash at runtime — but no source string uses a
    # literal '%' outside the "%@" placeholders already converted above,
    # so nothing further to escape here today.
    return value


def write_locale(locale: str, entries: dict, out_dir: pathlib.Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "strings.xml"

    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        f"<!-- Generated by i18n/generate-android-strings.py from i18n/source/{locale}.json — do not hand-edit. -->",
        "<resources>",
    ]
    for key, value in entries.items():
        if key.startswith("_"):
            continue
        lines.append(f'    <string name="{resource_name(key)}">{escape(value)}</string>')
    lines.append("</resources>")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_path.relative_to(REPO_ROOT)} ({len(entries)} keys)")


def main() -> None:
    for source_path in sorted(SOURCE_DIR.glob("*.json")):
        locale = source_path.stem
        with open(source_path, encoding="utf-8") as f:
            entries = json.load(f)

        # Android's default values/ directory holds the base (English)
        # locale; every other locale gets its own values-<locale>/
        # qualifier — "ar" maps directly to Android's own "ar" qualifier,
        # which also carries automatic RTL layout mirroring (spec §9's
        # RTL-verification requirement, no separate flag needed).
        out_dir = OUT_DIR / "values" if locale == "en" else OUT_DIR / f"values-{locale}"
        write_locale(locale, entries, out_dir)


if __name__ == "__main__":
    main()
