#!/usr/bin/env python3
"""Generates Apple .strings files from i18n/source/<locale>.json (spec §9:
"generate each platform's native format from it"). Run this whenever a
source/*.json file changes, then re-run `xcodegen generate` in
apps/macos/ so the new/changed .lproj folders are picked up.

Usage: python3 i18n/generate-apple-strings.py
"""
import json
import pathlib

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE_DIR = REPO_ROOT / "i18n" / "source"
OUT_DIR = REPO_ROOT / "apps" / "macos" / "VaultSigner" / "Resources"


def escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main() -> None:
    for source_path in sorted(SOURCE_DIR.glob("*.json")):
        locale = source_path.stem
        with open(source_path, encoding="utf-8") as f:
            entries = json.load(f)

        lproj_dir = OUT_DIR / f"{locale}.lproj"
        lproj_dir.mkdir(parents=True, exist_ok=True)
        out_path = lproj_dir / "Localizable.strings"

        lines = [
            "/* Generated by i18n/generate-apple-strings.py from "
            f"i18n/source/{locale}.json — do not hand-edit. */",
            "",
        ]
        for key, value in entries.items():
            if key.startswith("_"):
                continue
            lines.append(f'"{escape(key)}" = "{escape(value)}";')

        out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"wrote {out_path.relative_to(REPO_ROOT)} ({len(entries)} keys)")


if __name__ == "__main__":
    main()
