#!/bin/bash
# Regenerates the gh-pages branch (published as the GitHub Pages site)
# from the current documentation. gh-pages is a build output, never
# hand-edited directly — this script is the only thing that should
# ever write to it.
#
# Rebuilds gh-pages as an orphan branch (no shared history with the
# code branches, which is the standard, expected shape for a Pages
# branch) inside a temporary git worktree, so your actual working tree
# is never touched. Run this whenever any of the copied docs change,
# then push gh-pages.
#
# Run this from staging, release, or main — a branch with every
# platform's docs actually merged in. This file lives on `shared`
# since it's shared-scope tooling, but `shared` itself never receives
# platform-only paths like apps/macos/docs/ (see CLAUDE.md's branch
# model), so running it there would fail to find them.
#
# Usage: ./Scripts/build-docs-site.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKTREE_DIR="$(mktemp -d)"

# path -> Pages <title>, as parallel arrays (not an associative array —
# the macOS-shipped /bin/bash is 3.2, which predates `declare -A`; this
# needs to run correctly there without anyone needing a newer bash).
DOC_PATHS=(
    "README.md"
    "PROGRESS.md"
    "CHANGELOG.md"
    "spec/VaultSigner-Spec.md"
    "docs/user-guide.md"
    "docs/protocol-integration/README.md"
    "docs/protocol-integration/PROTOCOL-SPEC.md"
    "apps/macos/README.md"
    "apps/macos/docs/protocol-integration.md"
    "apps/windows/README.md"
    "apps/windows/docs/protocol-integration.md"
)
DOC_TITLES=(
    "VaultSigner"
    "Implementation Progress"
    "Changelog"
    "Specification"
    "User Guide"
    "Protocol Integration"
    "Protocol Specification"
    "macOS Developer Notes"
    "macOS Protocol Integration"
    "Windows Developer Notes"
    "Windows Protocol Integration"
)

cleanup() { git -C "$REPO_ROOT" worktree remove --force "$WORKTREE_DIR" 2>/dev/null || true; }
trap cleanup EXIT

echo "build-docs-site.sh: preparing worktree at $WORKTREE_DIR..."
git -C "$REPO_ROOT" worktree add --detach "$WORKTREE_DIR" >/dev/null
cd "$WORKTREE_DIR"

if git show-ref --quiet refs/heads/gh-pages; then
    git checkout gh-pages
    git rm -rf . >/dev/null
else
    git checkout --orphan gh-pages
    git rm -rf . >/dev/null 2>&1 || true
fi

i=0
while [[ $i -lt ${#DOC_PATHS[@]} ]]; do
    rel="${DOC_PATHS[$i]}"
    title="${DOC_TITLES[$i]}"
    mkdir -p "$(dirname "$rel")"
    {
        echo "---"
        echo "title: $title"
        echo "---"
        echo
        cat "$REPO_ROOT/$rel"
    } > "$rel"
    i=$((i + 1))
done

cat > _config.yml <<'EOF'
theme: jekyll-theme-cayman
title: VaultSigner
description: A portable, compact, multi-platform cryptographic signer.
markdown: kramdown
EOF

cat > index.md <<'EOF'
---
title: VaultSigner
---

A portable, compact, multi-platform cryptographic signer.

## Guides

- [User Guide](docs/user-guide.md) — for people using the app day to day.
- [Protocol Integration](docs/protocol-integration/README.md) — for developers building an app that asks VaultSigner to sign something.
  - [macOS specifics](apps/macos/docs/protocol-integration.md)
  - [Windows specifics](apps/windows/docs/protocol-integration.md)
  - [Formal protocol specification](docs/protocol-integration/PROTOCOL-SPEC.md) — the normative wire-format reference.

## Reference

- [Specification](spec/VaultSigner-Spec.md) — the full product and engineering spec.
- [Implementation Progress](PROGRESS.md) — what's built, verified, and what's known-incomplete, per platform.
- [Changelog](CHANGELOG.md) — what shipped in each release.

## Platforms

- [macOS](apps/macos/README.md) — the first shipped platform.
- [Windows](apps/windows/README.md)

Source: [github.com/am-reis/vault_signer](https://github.com/am-reis/vault_signer)
EOF

git add -A
if git diff --cached --quiet; then
    echo "build-docs-site.sh: no changes since the last publish."
    exit 0
fi
git commit -m "Publish documentation site

Mirrors the current README, PROGRESS, CHANGELOG, spec, user guide, and
protocol integration docs with Jekyll front matter added for GitHub
Pages. Regenerated by Scripts/build-docs-site.sh - never hand-edited."

echo
echo "build-docs-site.sh: committed. Push it with:"
echo "  git push origin gh-pages"
